version: '3.3'

networks:
  local_network:
    ipam:
      driver: default
      config:
        - subnet: 154.0.0.0/16

services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: [ "CMD-SHELL", "exit 0" ]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      local_network:
        ipv4_address: 154.0.0.7

  kafka:
    container_name: kafka
    hostname: kafka
    image: confluentinc/cp-kafka:latest
    volumes:
      - ./broker/data:/var/lib/kafka/da
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema_registry:8082
    depends_on:
      - zookeeper
    healthcheck:
      test: [ "CMD-SHELL", "exit 0" ]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      local_network:
        ipv4_address: 154.0.0.8

  kafka_config:
    container_name: kafka_config
    hostname: kafka_config
    image: confluentinc/cp-kafka:latest
    entrypoint: /bin/sh -c
    volumes:
      - ./kafka:/tmp/kafka
    command: /tmp/kafka/./commands.sh
    depends_on:
      - kafka
      - schema_registry
    healthcheck:
      test: [ "CMD-SHELL", "exit 0" ]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      local_network:
        ipv4_address: 154.0.0.9

  schema_registry:
    container_name: schema_registry
    image: confluentinc/cp-schema-registry:latest
    hostname: schema_registry
    ports:
      - 8082:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
      - zookeeper
      - kafka
    healthcheck:
      test: [ "CMD-SHELL", "exit 0" ]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      local_network:
        ipv4_address: 154.0.0.10

  kafka_control_center:
    container_name: kafka_control_center
    image: confluentinc/cp-enterprise-control-center:5.4.0
    hostname: kafka_control_center
    depends_on:
      - zookeeper
      - schema_registry
      - kafka
    ports:
      - 9021:9021
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema_registry:8082"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    networks:
      local_network:
        ipv4_address: 154.0.0.11

  

